apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: contrail-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contrail-frontend
    spec:
      containers:
      - name: contrail-frontend
        image: savvythru/contrail-frontend-app
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: contrail-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: contrail-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
